# Generated by Django 3.0.5 on 2020-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='tablica/images/')),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=260, unique=True)),
            ],
        ),
    ]
