# Generated by Django 3.0.5 on 2020-08-16 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='paragraph1',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
