# Generated by Django 3.0.5 on 2020-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablica', '0002_auto_20200816_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='paragraph1',
            new_name='paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, upload_to='tablica/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, upload_to='tablica/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, upload_to='tablica/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, upload_to='tablica/images/'),
        ),
    ]
